#pragma once

// GENERATED by ZynForgeBrand/generate.py -- DO NOT EDIT.
// Source: tokens.json (sha256:857c0847a54e). Edit tokens.json, re-run
// the generator, and re-vendor this file into the consuming app.

namespace zynforge::forge
{
    inline constexpr const char* tokensHash = "857c0847a54e";

    // ── Colours (0xAARRGGBB) ──
    inline constexpr unsigned int brandOrange = 0xffff7733;
    inline constexpr unsigned int brandDeep = 0xff0a0a0f;
    inline constexpr unsigned int bgDeep = 0xff0d0d12;
    inline constexpr unsigned int bgPanel = 0xff121316;
    inline constexpr unsigned int bgStrip = 0xff1e1e1e;
    inline constexpr unsigned int bgElevated = 0xff303030;
    inline constexpr unsigned int edge = 0xff26282e;
    inline constexpr unsigned int borderSubtle = 0xff3a3a3a;
    inline constexpr unsigned int borderBright = 0xff5a5a5a;
    inline constexpr unsigned int inputBg = 0xff000000;
    inline constexpr unsigned int accentEdit = 0xff3a90e0;
    inline constexpr unsigned int textPrimary = 0xffffffff;
    inline constexpr unsigned int textSecondary = 0xffb8c2cc;
    inline constexpr unsigned int textTertiary = 0xff7a8a9a;
    inline constexpr unsigned int textMuted = 0xff55606c;
    inline constexpr unsigned int accentRecord = 0xffff3b3b;
    inline constexpr unsigned int accentPlay = 0xff4ad878;
    inline constexpr unsigned int accentVS = 0xffffb42a;
    inline constexpr unsigned int accentStatus = 0xff5dd87a;
    inline constexpr unsigned int accentSolo = 0xffffd64d;
    inline constexpr unsigned int alertAmber = 0xffe89827;
    inline constexpr unsigned int engagedAmber = 0xffff9e2c;
    inline constexpr unsigned int featureEngaged = 0xff33c4d4;
    inline constexpr unsigned int meterGreen = 0xff3cb878;
    inline constexpr unsigned int meterAmber = 0xfff0c060;
    inline constexpr unsigned int meterRed = 0xffdc3838;
    inline constexpr unsigned int meterIdle = 0xff2c303a;
    inline constexpr unsigned int meterEmber = 0xffe05518;
    inline constexpr unsigned int meterHot = 0xffff8a24;
    inline constexpr unsigned int meterWhiteHot = 0xffffefcf;
    inline constexpr unsigned int controlBg = 0xff2a2c30;
    inline constexpr unsigned int controlBgHover = 0xff36383e;
    inline constexpr unsigned int controlBgDown = 0xff3e4046;
    inline constexpr unsigned int controlBorder = 0xff141518;
    inline constexpr unsigned int faderThumbHi = 0xff33353c;
    inline constexpr unsigned int faderThumbLo = 0xff1c1e23;
    inline constexpr unsigned int faderThumbEdge = 0xff555760;
    inline constexpr unsigned int faderThumbGrip = 0xffa0a3ad;
    inline constexpr unsigned int swatchSlate = 0xff404550;
    inline constexpr unsigned int swatchGraphite = 0xff55555a;
    inline constexpr unsigned int stripDefaultGrey = 0xff53555b;

    // ── Personality rotation (INS 1-8) ──
    inline constexpr unsigned int personality[8] = {
        0xff4c6c88, 0xff528a6a, 0xff807646, 0xff765a8c, 0xff783c4e, 0xff3c8286, 0xff805c32, 0xff7a6a38
    };

    // ── Forge-heat meter ramp stops (height fraction) ──
    inline constexpr float heat_whiteHotAbove = 0.95f;
    inline constexpr float heat_hotAbove = 0.85f;
    inline constexpr float heat_emberAbove = 0.7f;

    // ── alpha ──
    inline constexpr float alpha_faint = 0.1f;
    inline constexpr float alpha_chrome = 0.12f;
    inline constexpr float alpha_edgeSoft = 0.16f;
    inline constexpr float alpha_subtle = 0.18f;
    inline constexpr float alpha_wash = 0.3f;
    inline constexpr float alpha_dimmed = 0.35f;
    inline constexpr float alpha_ghost = 0.4f;
    inline constexpr float alpha_scrim = 0.45f;
    inline constexpr float alpha_muted = 0.55f;
    inline constexpr float alpha_prominent = 0.85f;
    inline constexpr float alpha_bold = 0.95f;

    // ── shadow ──
    inline constexpr float shadow_elev1 = 0.25f;
    inline constexpr float shadow_elev2 = 0.4f;
    inline constexpr float shadow_elev3 = 0.55f;

    // ── motion ──
    inline constexpr int motion_quickFadeMs = 200;
    inline constexpr int motion_fadeOutMs = 320;
    inline constexpr int motion_toastHoldMs = 2800;
    inline constexpr int motion_clipLatchMs = 1000;
    inline constexpr float motion_pulseHz = 1.0f;
    inline constexpr float motion_cueRampSec = 0.5f;
    inline constexpr int motion_launchDelayMs = 250;

    // ── radius ──
    inline constexpr float radius_sm = 2.5f;
    inline constexpr float radius_md = 4.0f;
    inline constexpr float radius_lg = 5.0f;
    inline constexpr float radius_xl = 8.0f;

    // ── space ──
    inline constexpr int space_xs = 4;
    inline constexpr int space_sm = 6;
    inline constexpr int space_md = 8;
    inline constexpr int space_lg = 10;
    inline constexpr int space_xl = 16;
    inline constexpr int space_ctrlH = 22;
    inline constexpr int space_ioH = 20;
    inline constexpr int space_rowH = 26;
    inline constexpr int space_btnH = 24;

    // ── type ──
    inline constexpr const char* uiFamily   = "Inter";
    inline constexpr const char* monoFamily = "JetBrains Mono";
    inline constexpr float type_micro = 9.5f;
    inline constexpr float type_label = 10.0f;
    inline constexpr float type_caption = 11.0f;
    inline constexpr float type_body = 13.0f;
    inline constexpr float type_title = 14.0f;
    inline constexpr float type_headline = 18.0f;
    inline constexpr float type_subhead = 22.0f;
    inline constexpr float type_display = 28.0f;
    inline constexpr float type_hero = 44.0f;

    // ── Per-app accents ──
    inline constexpr unsigned int accent_recording = 0xffff7733;   // shipped -- the reference implementation
    inline constexpr unsigned int accent_live = 0xffff7733;   // shipped -- shares the forge orange with Recording (console family)
    inline constexpr unsigned int accent_stage = 0xffe8a13c;   // shipped -- warm analog-console gold; Stage also keeps its documented warm-charcoal SURFACE variant
    inline constexpr unsigned int accent_defeedback = 0xffff9b3d;   // shipped -- plugin amber
    inline constexpr unsigned int accent_acoustic = 0xffe0a458;   // shipped -- treatment gold (accent2 blue stays app-local)
    inline constexpr unsigned int accent_speakers = 0xff5aa9e6;   // shipped -- placement blue (accent2 gold stays app-local)
}
